version: "3"

services:
  boot:
    image: kuzoncby/spring-boot-websocket-chat-demo:1.0.0
    build:
      context: .
    hostname: boot
    container_name: boot
    ports:
      - 5273:5273
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/skywalking/agent/skywalking-agent.jar -Xms100m -Xmx100m  -Duser.timezone=Asia/Shanghai -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom
      - SW_AGENT_NAME=spring-boot-websocket-chat-demo
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=oap:11800
