version: "3"

services:
  boot:
    image: kuzoncby/spring-boot-websocket-chat-demo:1.0.0
    build:
      context: .
    hostname: boot
    container_name: boot
    ports:
      - 5273:5273
    environment:
      - SPRING_PROFILES_ACTIVE=local
